In [1]:
import random
import numpy as np

In [2]:
random_bias_uniform_distribution_500_1000 = np.random.uniform(500,1000,[1,2000])

In [3]:
random_bias_uniform_distribution_500_1000 = np.round(random_bias_uniform_distribution_500_1000, decimals=1)

In [4]:
random_bias_uniform_distribution_500_1000

array([[650.9, 698.5, 778.2, ..., 640.3, 996.1, 694.3]])

In [5]:
np.savetxt('2000_random_bias_uniform_distribution_500_1000.txt',random_bias_uniform_distribution_500_1000,fmt='%0.8f')#数据存储

In [6]:
beta= np.loadtxt("2000_random_bias_uniform_distribution_500_1000.txt")

In [7]:
beta

array([650.9, 698.5, 778.2, ..., 640.3, 996.1, 694.3])

In [1]:
import random
import numpy as np

In [2]:
random_bias_uniform_distribution_0_500 = np.random.uniform(0,500,[1,2000])

In [3]:
random_bias_uniform_distribution_0_500 = np.round(random_bias_uniform_distribution_0_500, decimals=1)

In [4]:
random_bias_uniform_distribution_0_500

array([[259.3,  56.1, 167. , ...,  55.3, 496.8,  81.3]])

In [5]:
np.savetxt('2000_random_bias_uniform_distribution_0_500.txt',random_bias_uniform_distribution_0_500,fmt='%0.8f')#数据存储

In [6]:
beta= np.loadtxt("2000_random_bias_uniform_distribution_0_500.txt")

In [7]:
beta

array([259.3,  56.1, 167. , ...,  55.3, 496.8,  81.3])

小值高斯分布

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import random
from sympy import *
import math

In [2]:
mu1 = 60  #期望
sigma1 = 10  #标准差
num1 = 2000  #个数

In [3]:
random_bias_normal_distribution1 = np.random.normal(mu1, sigma1, num1)

In [4]:
random_bias_normal_distribution1 = np.round(random_bias_normal_distribution1, decimals=1)

In [5]:
random_bias_normal_distribution1

array([79.9, 71.7, 75.6, ..., 65.3, 62.1, 52.4])

In [6]:
min(random_bias_normal_distribution1)

np.float64(26.9)

In [7]:
max(random_bias_normal_distribution1)

np.float64(92.7)

In [8]:
np.savetxt('2000_Gaussian_distribution_(60,10).txt',random_bias_normal_distribution1,fmt='%0.8f')#数据存储

In [ ]:
beta1= np.loadtxt("2000_normal_distribution_(60,10).txt")

大值高斯分布

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import random
from sympy import *
import math

In [2]:
mu1 = 600  #期望
sigma1 = 10  #标准差
num1 = 2000  #个数

In [3]:
random_bias_normal_distribution1 = np.random.normal(mu1, sigma1, num1)

In [4]:
random_bias_normal_distribution1 = np.round(random_bias_normal_distribution1, decimals=1)

In [5]:
random_bias_normal_distribution1

array([600. , 597.7, 598.1, ..., 593.7, 611. , 613.5])

In [6]:
min(random_bias_normal_distribution1)

np.float64(566.5)

In [7]:
max(random_bias_normal_distribution1)

np.float64(631.6)

In [8]:
np.savetxt('2000_Gaussian_distribution_(600,10).txt',random_bias_normal_distribution1,fmt='%0.8f')#数据存储

In [ ]:
beta1= np.loadtxt("2000_normal_distribution_(600,10).txt")