In [1]:
import random
import numpy as np

In [2]:
random_bias_uniform_distribution_500_1000 = np.random.uniform(500,1000,[1,2000])

In [3]:
random_bias_uniform_distribution_500_1000 = np.round(random_bias_uniform_distribution_500_1000, decimals=1)

In [4]:
random_bias_uniform_distribution_500_1000

array([[650.9, 698.5, 778.2, ..., 640.3, 996.1, 694.3]])

In [5]:
np.savetxt('2000_random_bias_uniform_distribution_500_1000.txt',random_bias_uniform_distribution_500_1000,fmt='%0.8f')#数据存储

In [6]:
beta= np.loadtxt("2000_random_bias_uniform_distribution_500_1000.txt")

In [7]:
beta

array([650.9, 698.5, 778.2, ..., 640.3, 996.1, 694.3])

In [1]:
import random
import numpy as np

In [2]:
random_bias_uniform_distribution_0_500 = np.random.uniform(0,500,[1,2000])

In [3]:
random_bias_uniform_distribution_0_500 = np.round(random_bias_uniform_distribution_0_500, decimals=1)

In [4]:
random_bias_uniform_distribution_0_500

array([[259.3,  56.1, 167. , ...,  55.3, 496.8,  81.3]])

In [5]:
np.savetxt('2000_random_bias_uniform_distribution_0_500.txt',random_bias_uniform_distribution_0_500,fmt='%0.8f')#数据存储

In [6]:
beta= np.loadtxt("2000_random_bias_uniform_distribution_0_500.txt")

In [7]:
beta

array([259.3,  56.1, 167. , ...,  55.3, 496.8,  81.3])

小值高斯分布

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import random
from sympy import *
import math

In [2]:
mu1 = 50  #期望
sigma1 = 10  #标准差
num1 = 1000  #个数

In [3]:
random_bias_normal_distribution1 = np.random.normal(mu1, sigma1, num1)

In [4]:
random_bias_normal_distribution1 = np.round(random_bias_normal_distribution1, decimals=1)

In [5]:
random_bias_normal_distribution1

array([55.3, 39.5, 64.2, 56. , 65. , 64.7, 32.7, 42.5, 64.4, 52.7, 55. ,
       51.1, 63.6, 54.6, 49. , 57.1, 34.2, 43.7, 46.9, 42.1, 59.7, 45.8,
       54.5, 69.4, 38.7, 40.3, 35.5, 54.8, 55.8, 60.4, 62.6, 54.6, 53.5,
       52.8, 45.3, 47. , 52.1, 36. , 49.2, 59.7, 48.9, 39.5, 49.4, 58.6,
       59.1, 45.4, 65.2, 57.4, 53.2, 41.9, 53.5, 59.4, 35.8, 53. , 55.7,
       57.7, 47.9, 59.2, 53.1, 46.7, 48.4, 55.7, 53.1, 42. , 58.5, 55.1,
       50.5, 40. , 52.7, 57.7, 52.4, 39.4, 73.2, 51.2, 54.3, 56.3, 65.4,
       60.1, 37.3, 41.4, 53.4, 63.4, 50.5, 45. , 45.6, 43.1, 35.9, 52.7,
       52.9, 32.2, 61.4, 53.5, 53.5, 42.3, 32.8, 48.8, 53.3, 53.1, 38.6,
       58.1, 51.9, 26. , 55.8, 60.4, 42.8, 47.3, 51.1, 37.5, 54.1, 58.5,
       56.8, 62.4, 48.2, 38.8, 42.2, 60.6, 49.6, 59.8, 53.4, 36.1, 53.5,
       49.1, 67.1, 49.1, 62.5, 57.8, 46.3, 31.2, 32.1, 44.3, 49.4, 47.2,
       49.5, 36. , 50.5, 46.8, 47.1, 27.2, 50.8, 44.2, 43.6, 39.4, 48.9,
       66.2, 49.1, 51.8, 43.7, 55.3, 52.5, 49.4, 57

In [6]:
min(random_bias_normal_distribution1)

np.float64(21.4)

In [7]:
max(random_bias_normal_distribution1)

np.float64(76.1)

In [8]:
np.savetxt('1000_Gaussian_distribution_(50,10).txt',random_bias_normal_distribution1,fmt='%0.8f')#数据存储

In [ ]:
beta1= np.loadtxt("1000_normal_distribution_(50,10).txt")

大值高斯分布

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import random
from sympy import *
import math

In [2]:
mu1 = 500  #期望
sigma1 = 10  #标准差
num1 = 1000  #个数

In [3]:
random_bias_normal_distribution1 = np.random.normal(mu1, sigma1, num1)

In [4]:
random_bias_normal_distribution1 = np.round(random_bias_normal_distribution1, decimals=1)

In [5]:
random_bias_normal_distribution1

array([509.4, 514.2, 495.6, 484.8, 508.6, 523.4, 501.9, 496.3, 499.9,
       488.7, 491.8, 499.2, 512.2, 501.7, 502.7, 506.8, 505. , 493.8,
       490.1, 521. , 491. , 519.5, 506.1, 485.9, 514.8, 499.5, 500.6,
       510.7, 498.5, 499.5, 505.7, 503.5, 492.7, 495.5, 480.6, 502.5,
       488.8, 495.4, 504.5, 492. , 511. , 505.9, 508.4, 499.9, 491.8,
       481.1, 499.2, 505.9, 503. , 500.8, 500.8, 492.7, 503.2, 512.3,
       493.1, 511.5, 508.9, 486.7, 525.1, 499. , 503.2, 504. , 512.7,
       497.9, 489. , 497.4, 508.4, 512.4, 498.9, 513.2, 500. , 507.4,
       492.9, 497.4, 500.2, 509.9, 525.2, 495.3, 495.2, 495.1, 505.2,
       492.3, 494.2, 487.9, 501.3, 502.2, 481.5, 484.6, 500.5, 510.6,
       498.8, 507.9, 503.8, 496.5, 484.6, 509.8, 502.5, 509.3, 501.3,
       507.4, 518. , 493.7, 503.8, 495.7, 505.5, 485.4, 490.7, 507.6,
       508.3, 491.3, 493.9, 512.3, 494.4, 487.6, 492.7, 508.2, 515.6,
       498.9, 506.9, 473.6, 505.3, 504.4, 495.2, 504. , 490.7, 514.9,
       495.4, 500.9,

In [6]:
min(random_bias_normal_distribution1)

np.float64(468.2)

In [7]:
max(random_bias_normal_distribution1)

np.float64(531.2)

In [8]:
np.savetxt('1000_Gaussian_distribution_(500,10).txt',random_bias_normal_distribution1,fmt='%0.8f')#数据存储

In [ ]:
beta1= np.loadtxt("1000_normal_distribution_(500,10).txt")